apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: y3wzuczcl-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/y3wzuczcl-java-springboot-gitops